name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}